readingIsGood:
  jwtSecret: readingIsGoodSecretKey
  jwtExpirationMs: 86400000

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: readingisgood
    password: readingisgood
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method